CREATE TABLE USERS
(
    ID       SERIAL,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL    VARCHAR(100) NOT NULL,
    NAME     VARCHAR(100) NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME);
ALTER TABLE USERS ADD CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL);
ALTER TABLE USERS ADD CONSTRAINT CK_PASSWORD CHECK (LENGTH(PASSWORD) >= 8);
